version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: /data/load-redis.sh cache
    networks:
      - backend
    depends_on:
      cache:
        condition: service_started

  voter-api:
    image: voter-api:v2
    container_name: voter-api-1
    restart: always
    ports:
      - 1080:1080
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  votes-api:
    image: votes-api
    container_name: votes-api-1
    restart: always
    ports:
      - 1081:1081
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
    
  poll-api:
    image: poll-api
    container_name: poll-api-1
    restart: always
    ports:
      - 1082:1082
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend 

networks:
  frontend:
    internal: false
  backend:
    internal: true