version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  voter-api:
    image: voter-api:v2
    container_name: voter-api-1
    restart: always
    ports:
      - 1080:1080
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend

  votes-api:
    image: votes-api
    container_name: votes-api-1
    restart: always
    ports:
      - 1081:1080
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
      - VOTER_API_URL=http://voter-api:1080 
      - POLL_API_URL=http://poll-api:1082 
    networks:
      - frontend
      - backend
    
  poll-api:
    image: poll-api
    container_name: poll-api-1
    restart: always
    ports:
      - 1082:1080
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend 

networks:
  frontend:
    internal: false
  backend:
    internal: true